// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module mlp_dance3_mlp_dance3_Pipeline_loadbias3_pos (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        S_AXIS_V_TVALID,
        bias_3_pos_2_03,
        bias_3_pos_1_02,
        bias_3_pos_0_01,
        S_AXIS_V_TDATA,
        S_AXIS_V_TREADY,
        bias_3_pos_2_1_out,
        bias_3_pos_2_1_out_ap_vld,
        bias_3_pos_1_1_out,
        bias_3_pos_1_1_out_ap_vld,
        bias_3_pos_0_1_out,
        bias_3_pos_0_1_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   S_AXIS_V_TVALID;
input  [31:0] bias_3_pos_2_03;
input  [31:0] bias_3_pos_1_02;
input  [31:0] bias_3_pos_0_01;
input  [63:0] S_AXIS_V_TDATA;
output   S_AXIS_V_TREADY;
output  [31:0] bias_3_pos_2_1_out;
output   bias_3_pos_2_1_out_ap_vld;
output  [31:0] bias_3_pos_1_1_out;
output   bias_3_pos_1_1_out_ap_vld;
output  [31:0] bias_3_pos_0_1_out;
output   bias_3_pos_0_1_out_ap_vld;

reg ap_idle;
reg S_AXIS_V_TREADY;
reg bias_3_pos_2_1_out_ap_vld;
reg bias_3_pos_1_1_out_ap_vld;
reg bias_3_pos_0_1_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln130_fu_136_p2;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    S_AXIS_V_TDATA_blk_n;
reg   [1:0] i_fu_52;
wire    ap_loop_init;
reg   [1:0] ap_sig_allocacmp_i_6;
wire   [1:0] add_ln130_fu_142_p2;
wire   [1:0] i_6_load_fu_133_p1;
reg   [31:0] bias_3_pos_1_fu_56;
wire   [31:0] bias_3_pos_1_4_fu_152_p1;
reg   [31:0] bias_3_pos_1_1_fu_60;
reg   [31:0] bias_3_pos_1_2_fu_64;
wire   [31:0] trunc_ln145_fu_148_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
reg    ap_condition_130;
reg    ap_condition_85;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

mlp_dance3_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_start_int == 1'b0) | ((1'b0 == S_AXIS_V_TVALID) & (icmp_ln130_fu_136_p2 == 1'd0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_130)) begin
        if (((i_6_load_fu_133_p1 == 2'd1) & (icmp_ln130_fu_136_p2 == 1'd0))) begin
            bias_3_pos_1_1_fu_60 <= bias_3_pos_1_4_fu_152_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            bias_3_pos_1_1_fu_60 <= bias_3_pos_1_02;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_130)) begin
        if ((1'b1 == ap_condition_85)) begin
            bias_3_pos_1_2_fu_64 <= bias_3_pos_1_4_fu_152_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            bias_3_pos_1_2_fu_64 <= bias_3_pos_2_03;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_130)) begin
        if (((i_6_load_fu_133_p1 == 2'd0) & (icmp_ln130_fu_136_p2 == 1'd0))) begin
            bias_3_pos_1_fu_56 <= bias_3_pos_1_4_fu_152_p1;
        end else if ((ap_loop_init == 1'b1)) begin
            bias_3_pos_1_fu_56 <= bias_3_pos_0_01;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_130)) begin
        if ((icmp_ln130_fu_136_p2 == 1'd0)) begin
            i_fu_52 <= add_ln130_fu_142_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_52 <= 2'd0;
        end
    end
end

always @ (*) begin
    if (((icmp_ln130_fu_136_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        S_AXIS_V_TDATA_blk_n = S_AXIS_V_TVALID;
    end else begin
        S_AXIS_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == S_AXIS_V_TVALID) & (icmp_ln130_fu_136_p2 == 1'd0))) & (icmp_ln130_fu_136_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        S_AXIS_V_TREADY = 1'b1;
    end else begin
        S_AXIS_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) | ((1'b0 == S_AXIS_V_TVALID) & (icmp_ln130_fu_136_p2 == 1'd0)))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == S_AXIS_V_TVALID) & (icmp_ln130_fu_136_p2 == 1'd0))) & (icmp_ln130_fu_136_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == S_AXIS_V_TVALID) & (icmp_ln130_fu_136_p2 == 1'd0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == S_AXIS_V_TVALID) & (icmp_ln130_fu_136_p2 == 1'd0))) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_i_6 = 2'd0;
    end else begin
        ap_sig_allocacmp_i_6 = i_fu_52;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == S_AXIS_V_TVALID) & (icmp_ln130_fu_136_p2 == 1'd0))) & (icmp_ln130_fu_136_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        bias_3_pos_0_1_out_ap_vld = 1'b1;
    end else begin
        bias_3_pos_0_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == S_AXIS_V_TVALID) & (icmp_ln130_fu_136_p2 == 1'd0))) & (icmp_ln130_fu_136_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        bias_3_pos_1_1_out_ap_vld = 1'b1;
    end else begin
        bias_3_pos_1_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == S_AXIS_V_TVALID) & (icmp_ln130_fu_136_p2 == 1'd0))) & (icmp_ln130_fu_136_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        bias_3_pos_2_1_out_ap_vld = 1'b1;
    end else begin
        bias_3_pos_2_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln130_fu_142_p2 = (ap_sig_allocacmp_i_6 + 2'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((1'b0 == S_AXIS_V_TVALID) & (icmp_ln130_fu_136_p2 == 1'd0)));
end

always @ (*) begin
    ap_condition_130 = (~((ap_start_int == 1'b0) | ((1'b0 == S_AXIS_V_TVALID) & (icmp_ln130_fu_136_p2 == 1'd0))) & (1'b1 == ap_CS_fsm_state1));
end

always @ (*) begin
    ap_condition_85 = (~(i_6_load_fu_133_p1 == 2'd1) & ~(i_6_load_fu_133_p1 == 2'd0) & (icmp_ln130_fu_136_p2 == 1'd0));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign bias_3_pos_0_1_out = bias_3_pos_1_fu_56;

assign bias_3_pos_1_1_out = bias_3_pos_1_1_fu_60;

assign bias_3_pos_1_4_fu_152_p1 = trunc_ln145_fu_148_p1;

assign bias_3_pos_2_1_out = bias_3_pos_1_2_fu_64;

assign i_6_load_fu_133_p1 = ap_sig_allocacmp_i_6;

assign icmp_ln130_fu_136_p2 = ((ap_sig_allocacmp_i_6 == 2'd3) ? 1'b1 : 1'b0);

assign trunc_ln145_fu_148_p1 = S_AXIS_V_TDATA[31:0];

endmodule //mlp_dance3_mlp_dance3_Pipeline_loadbias3_pos
