// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="mlp_dance3_mlp_dance3,hls_ip_2021_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu3eg-sbva484-1-i,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.853400,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=5,HLS_SYN_DSP=0,HLS_SYN_FF=15359,HLS_SYN_LUT=10565,HLS_VERSION=2021_1}" *)

module mlp_dance3 (
        ap_clk,
        ap_rst_n,
        S_AXIS_V_TDATA,
        S_AXIS_V_TVALID,
        S_AXIS_V_TREADY,
        M_AXIS_V_TDATA,
        M_AXIS_V_TVALID,
        M_AXIS_V_TREADY
);

parameter    ap_ST_fsm_state1 = 18'd1;
parameter    ap_ST_fsm_state2 = 18'd2;
parameter    ap_ST_fsm_state3 = 18'd4;
parameter    ap_ST_fsm_state4 = 18'd8;
parameter    ap_ST_fsm_state5 = 18'd16;
parameter    ap_ST_fsm_state6 = 18'd32;
parameter    ap_ST_fsm_state7 = 18'd64;
parameter    ap_ST_fsm_state8 = 18'd128;
parameter    ap_ST_fsm_state9 = 18'd256;
parameter    ap_ST_fsm_state10 = 18'd512;
parameter    ap_ST_fsm_state11 = 18'd1024;
parameter    ap_ST_fsm_state12 = 18'd2048;
parameter    ap_ST_fsm_state13 = 18'd4096;
parameter    ap_ST_fsm_state14 = 18'd8192;
parameter    ap_ST_fsm_state15 = 18'd16384;
parameter    ap_ST_fsm_state16 = 18'd32768;
parameter    ap_ST_fsm_state17 = 18'd65536;
parameter    ap_ST_fsm_state18 = 18'd131072;

input   ap_clk;
input   ap_rst_n;
input  [63:0] S_AXIS_V_TDATA;
input   S_AXIS_V_TVALID;
output   S_AXIS_V_TREADY;
output  [63:0] M_AXIS_V_TDATA;
output   M_AXIS_V_TVALID;
input   M_AXIS_V_TREADY;

 reg    ap_rst_n_inv;
reg    S_AXIS_V_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [17:0] ap_CS_fsm;
wire    ap_CS_fsm_state9;
reg   [31:0] reg_679;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state13;
reg   [31:0] reg_685;
reg   [31:0] reg_691;
reg   [31:0] reg_697;
reg   [31:0] reg_703;
reg   [31:0] reg_709;
reg   [31:0] reg_715;
reg   [31:0] reg_721;
reg   [31:0] reg_727;
reg   [31:0] reg_733;
reg   [31:0] reg_739;
reg   [31:0] reg_745;
reg   [31:0] reg_751;
reg   [31:0] reg_757;
reg   [31:0] reg_763;
reg   [31:0] reg_769;
reg   [31:0] reg_775;
reg   [31:0] reg_781;
reg   [31:0] reg_787;
reg   [31:0] reg_793;
reg   [31:0] reg_799;
reg   [31:0] reg_805;
reg   [31:0] reg_811;
reg   [31:0] reg_817;
wire   [31:0] staged_3_load_fu_828_p1;
reg   [31:0] staged_3_reg_1651;
wire    ap_CS_fsm_state2;
wire   [31:0] in_data_fu_978_p1;
wire   [0:0] icmp_ln137_fu_997_p2;
reg   [0:0] icmp_ln137_reg_1727;
wire   [0:0] icmp_ln137_1_fu_1003_p2;
reg   [0:0] icmp_ln137_1_reg_1732;
wire   [31:0] select_ln142_fu_1019_p3;
wire    ap_CS_fsm_state10;
reg   [6:0] input_address0;
reg    input_ce0;
reg    input_we0;
wire   [31:0] input_q0;
reg    input_ce1;
wire   [31:0] input_q1;
reg   [9:0] weights_0_address0;
reg    weights_0_ce0;
reg    weights_0_we0;
wire   [31:0] weights_0_q0;
reg    weights_0_ce1;
wire   [31:0] weights_0_q1;
reg   [6:0] bias_0_address0;
reg    bias_0_ce0;
reg    bias_0_we0;
wire   [31:0] bias_0_q0;
wire    grp_mlp_dance3_Pipeline_layer0_fu_405_ap_start;
wire    grp_mlp_dance3_Pipeline_layer0_fu_405_ap_done;
wire    grp_mlp_dance3_Pipeline_layer0_fu_405_ap_idle;
wire    grp_mlp_dance3_Pipeline_layer0_fu_405_ap_ready;
wire   [6:0] grp_mlp_dance3_Pipeline_layer0_fu_405_input_r_address0;
wire    grp_mlp_dance3_Pipeline_layer0_fu_405_input_r_ce0;
wire   [6:0] grp_mlp_dance3_Pipeline_layer0_fu_405_input_r_address1;
wire    grp_mlp_dance3_Pipeline_layer0_fu_405_input_r_ce1;
wire   [9:0] grp_mlp_dance3_Pipeline_layer0_fu_405_weights_0_address0;
wire    grp_mlp_dance3_Pipeline_layer0_fu_405_weights_0_ce0;
wire   [9:0] grp_mlp_dance3_Pipeline_layer0_fu_405_weights_0_address1;
wire    grp_mlp_dance3_Pipeline_layer0_fu_405_weights_0_ce1;
wire   [6:0] grp_mlp_dance3_Pipeline_layer0_fu_405_bias_0_address0;
wire    grp_mlp_dance3_Pipeline_layer0_fu_405_bias_0_ce0;
wire   [31:0] grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_7_1_out;
wire    grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_7_1_out_ap_vld;
wire   [31:0] grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_6_1_out;
wire    grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_6_1_out_ap_vld;
wire   [31:0] grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_5_1_out;
wire    grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_5_1_out_ap_vld;
wire   [31:0] grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_4_1_out;
wire    grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_4_1_out_ap_vld;
wire   [31:0] grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_3_1_out;
wire    grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_3_1_out_ap_vld;
wire   [31:0] grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_2_1_out;
wire    grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_2_1_out_ap_vld;
wire   [31:0] grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_1_1_out;
wire    grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_1_1_out_ap_vld;
wire   [31:0] grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_0_1_out;
wire    grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_0_1_out_ap_vld;
wire   [31:0] grp_mlp_dance3_Pipeline_layer0_fu_405_grp_fu_1742_p_din0;
wire   [31:0] grp_mlp_dance3_Pipeline_layer0_fu_405_grp_fu_1742_p_din1;
wire   [1:0] grp_mlp_dance3_Pipeline_layer0_fu_405_grp_fu_1742_p_opcode;
wire    grp_mlp_dance3_Pipeline_layer0_fu_405_grp_fu_1742_p_ce;
wire   [31:0] grp_mlp_dance3_Pipeline_layer0_fu_405_grp_fu_554_p_din0;
wire   [31:0] grp_mlp_dance3_Pipeline_layer0_fu_405_grp_fu_554_p_din1;
wire   [4:0] grp_mlp_dance3_Pipeline_layer0_fu_405_grp_fu_554_p_opcode;
wire    grp_mlp_dance3_Pipeline_layer0_fu_405_grp_fu_554_p_ce;
wire    grp_mlp_dance3_Pipeline_retrieve_inputs_fu_428_ap_start;
wire    grp_mlp_dance3_Pipeline_retrieve_inputs_fu_428_ap_done;
wire    grp_mlp_dance3_Pipeline_retrieve_inputs_fu_428_ap_idle;
wire    grp_mlp_dance3_Pipeline_retrieve_inputs_fu_428_ap_ready;
wire    grp_mlp_dance3_Pipeline_retrieve_inputs_fu_428_S_AXIS_V_TREADY;
wire   [6:0] grp_mlp_dance3_Pipeline_retrieve_inputs_fu_428_input_r_address0;
wire    grp_mlp_dance3_Pipeline_retrieve_inputs_fu_428_input_r_ce0;
wire    grp_mlp_dance3_Pipeline_retrieve_inputs_fu_428_input_r_we0;
wire   [31:0] grp_mlp_dance3_Pipeline_retrieve_inputs_fu_428_input_r_d0;
wire    grp_mlp_dance3_Pipeline_loadweights0_VITIS_LOOP_46_2_fu_435_ap_start;
wire    grp_mlp_dance3_Pipeline_loadweights0_VITIS_LOOP_46_2_fu_435_ap_done;
wire    grp_mlp_dance3_Pipeline_loadweights0_VITIS_LOOP_46_2_fu_435_ap_idle;
wire    grp_mlp_dance3_Pipeline_loadweights0_VITIS_LOOP_46_2_fu_435_ap_ready;
wire   [9:0] grp_mlp_dance3_Pipeline_loadweights0_VITIS_LOOP_46_2_fu_435_weights_0_address0;
wire    grp_mlp_dance3_Pipeline_loadweights0_VITIS_LOOP_46_2_fu_435_weights_0_ce0;
wire    grp_mlp_dance3_Pipeline_loadweights0_VITIS_LOOP_46_2_fu_435_weights_0_we0;
wire   [31:0] grp_mlp_dance3_Pipeline_loadweights0_VITIS_LOOP_46_2_fu_435_weights_0_d0;
wire    grp_mlp_dance3_Pipeline_loadweights0_VITIS_LOOP_46_2_fu_435_S_AXIS_V_TREADY;
wire    grp_mlp_dance3_Pipeline_layer1_fu_442_ap_start;
wire    grp_mlp_dance3_Pipeline_layer1_fu_442_ap_done;
wire    grp_mlp_dance3_Pipeline_layer1_fu_442_ap_idle;
wire    grp_mlp_dance3_Pipeline_layer1_fu_442_ap_ready;
wire   [31:0] grp_mlp_dance3_Pipeline_layer1_fu_442_buffer_1_2_1_out;
wire    grp_mlp_dance3_Pipeline_layer1_fu_442_buffer_1_2_1_out_ap_vld;
wire   [31:0] grp_mlp_dance3_Pipeline_layer1_fu_442_buffer_1_1_1_out;
wire    grp_mlp_dance3_Pipeline_layer1_fu_442_buffer_1_1_1_out_ap_vld;
wire   [31:0] grp_mlp_dance3_Pipeline_layer1_fu_442_buffer_1_0_1_out;
wire    grp_mlp_dance3_Pipeline_layer1_fu_442_buffer_1_0_1_out_ap_vld;
wire   [31:0] grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1742_p_din0;
wire   [31:0] grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1742_p_din1;
wire   [1:0] grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1742_p_opcode;
wire    grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1742_p_ce;
wire   [31:0] grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1746_p_din0;
wire   [31:0] grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1746_p_din1;
wire   [1:0] grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1746_p_opcode;
wire    grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1746_p_ce;
wire   [31:0] grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1750_p_din0;
wire   [31:0] grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1750_p_din1;
wire   [1:0] grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1750_p_opcode;
wire    grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1750_p_ce;
wire   [31:0] grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1754_p_din0;
wire   [31:0] grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1754_p_din1;
wire   [1:0] grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1754_p_opcode;
wire    grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1754_p_ce;
wire   [31:0] grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1758_p_din0;
wire   [31:0] grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1758_p_din1;
wire   [1:0] grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1758_p_opcode;
wire    grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1758_p_ce;
wire   [31:0] grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1762_p_din0;
wire   [31:0] grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1762_p_din1;
wire   [1:0] grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1762_p_opcode;
wire    grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1762_p_ce;
wire   [31:0] grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1766_p_din0;
wire   [31:0] grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1766_p_din1;
wire   [1:0] grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1766_p_opcode;
wire    grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1766_p_ce;
wire   [31:0] grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1770_p_din0;
wire   [31:0] grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1770_p_din1;
wire   [1:0] grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1770_p_opcode;
wire    grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1770_p_ce;
wire   [31:0] grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1774_p_din0;
wire   [31:0] grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1774_p_din1;
wire   [1:0] grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1774_p_opcode;
wire    grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1774_p_ce;
wire   [31:0] grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_554_p_din0;
wire   [31:0] grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_554_p_din1;
wire   [4:0] grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_554_p_opcode;
wire    grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_554_p_ce;
wire    grp_mlp_dance3_Pipeline_output_fu_484_ap_start;
wire    grp_mlp_dance3_Pipeline_output_fu_484_ap_done;
wire    grp_mlp_dance3_Pipeline_output_fu_484_ap_idle;
wire    grp_mlp_dance3_Pipeline_output_fu_484_ap_ready;
wire    grp_mlp_dance3_Pipeline_output_fu_484_M_AXIS_V_TREADY;
wire   [63:0] grp_mlp_dance3_Pipeline_output_fu_484_M_AXIS_V_TDATA;
wire    grp_mlp_dance3_Pipeline_output_fu_484_M_AXIS_V_TVALID;
wire    grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_ap_start;
wire    grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_ap_done;
wire    grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_ap_idle;
wire    grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_ap_ready;
wire    grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_S_AXIS_V_TREADY;
wire   [31:0] grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_7_2_2_out;
wire    grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_7_2_2_out_ap_vld;
wire   [31:0] grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_7_1_2_out;
wire    grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_7_1_2_out_ap_vld;
wire   [31:0] grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_7_0_2_out;
wire    grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_7_0_2_out_ap_vld;
wire   [31:0] grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_6_2_2_out;
wire    grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_6_2_2_out_ap_vld;
wire   [31:0] grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_6_1_2_out;
wire    grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_6_1_2_out_ap_vld;
wire   [31:0] grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_6_0_2_out;
wire    grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_6_0_2_out_ap_vld;
wire   [31:0] grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_5_2_2_out;
wire    grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_5_2_2_out_ap_vld;
wire   [31:0] grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_5_1_2_out;
wire    grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_5_1_2_out_ap_vld;
wire   [31:0] grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_5_0_2_out;
wire    grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_5_0_2_out_ap_vld;
wire   [31:0] grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_4_2_2_out;
wire    grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_4_2_2_out_ap_vld;
wire   [31:0] grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_4_1_2_out;
wire    grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_4_1_2_out_ap_vld;
wire   [31:0] grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_4_0_2_out;
wire    grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_4_0_2_out_ap_vld;
wire   [31:0] grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_3_2_2_out;
wire    grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_3_2_2_out_ap_vld;
wire   [31:0] grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_3_1_2_out;
wire    grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_3_1_2_out_ap_vld;
wire   [31:0] grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_3_0_2_out;
wire    grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_3_0_2_out_ap_vld;
wire   [31:0] grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_2_2_2_out;
wire    grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_2_2_2_out_ap_vld;
wire   [31:0] grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_2_1_2_out;
wire    grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_2_1_2_out_ap_vld;
wire   [31:0] grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_2_0_2_out;
wire    grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_2_0_2_out_ap_vld;
wire   [31:0] grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_1_2_2_out;
wire    grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_1_2_2_out_ap_vld;
wire   [31:0] grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_1_1_2_out;
wire    grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_1_1_2_out_ap_vld;
wire   [31:0] grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_1_0_2_out;
wire    grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_1_0_2_out_ap_vld;
wire   [31:0] grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_0_2_2_out;
wire    grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_0_2_2_out_ap_vld;
wire   [31:0] grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_0_1_2_out;
wire    grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_0_1_2_out_ap_vld;
wire   [31:0] grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_0_0_2_out;
wire    grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_0_0_2_out_ap_vld;
wire    grp_mlp_dance3_Pipeline_loadbias0_fu_547_ap_start;
wire    grp_mlp_dance3_Pipeline_loadbias0_fu_547_ap_done;
wire    grp_mlp_dance3_Pipeline_loadbias0_fu_547_ap_idle;
wire    grp_mlp_dance3_Pipeline_loadbias0_fu_547_ap_ready;
wire    grp_mlp_dance3_Pipeline_loadbias0_fu_547_S_AXIS_V_TREADY;
wire   [6:0] grp_mlp_dance3_Pipeline_loadbias0_fu_547_bias_0_address0;
wire    grp_mlp_dance3_Pipeline_loadbias0_fu_547_bias_0_ce0;
wire    grp_mlp_dance3_Pipeline_loadbias0_fu_547_bias_0_we0;
wire   [31:0] grp_mlp_dance3_Pipeline_loadbias0_fu_547_bias_0_d0;
reg   [31:0] ap_phi_mux_staged_2_phi_fu_376_p6;
reg   [31:0] staged_2_reg_372;
wire    ap_CS_fsm_state17;
reg    ap_block_state17_on_subcall_done;
wire    ap_CS_fsm_state18;
reg   [31:0] staged_1_reg_386;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
reg    grp_mlp_dance3_Pipeline_layer0_fu_405_ap_start_reg;
wire    ap_CS_fsm_state3;
reg    grp_mlp_dance3_Pipeline_retrieve_inputs_fu_428_ap_start_reg;
reg    grp_mlp_dance3_Pipeline_loadweights0_VITIS_LOOP_46_2_fu_435_ap_start_reg;
wire    ap_CS_fsm_state11;
reg    grp_mlp_dance3_Pipeline_layer1_fu_442_ap_start_reg;
wire    ap_CS_fsm_state5;
reg    grp_mlp_dance3_Pipeline_output_fu_484_ap_start_reg;
wire    ap_CS_fsm_state6;
reg    grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_ap_start_reg;
wire    ap_CS_fsm_state14;
reg    grp_mlp_dance3_Pipeline_loadbias0_fu_547_ap_start_reg;
wire    ap_CS_fsm_state16;
reg   [31:0] buffer_0_0_0546_fu_70;
reg   [31:0] buffer_0_1_0547_fu_74;
reg   [31:0] buffer_0_2_0548_fu_78;
reg   [31:0] buffer_0_3_0549_fu_82;
reg   [31:0] buffer_0_4_0550_fu_86;
reg   [31:0] buffer_0_5_0551_fu_90;
reg   [31:0] buffer_0_6_0552_fu_94;
reg   [31:0] buffer_0_7_0553_fu_98;
reg   [31:0] buffer_1_0_025_fu_102;
reg   [31:0] buffer_1_1_026_fu_106;
reg   [31:0] buffer_1_2_027_fu_110;
reg   [31:0] weights_1_0_0_01_fu_114;
reg   [31:0] weights_1_0_1_02_fu_118;
reg   [31:0] weights_1_0_2_03_fu_122;
reg   [31:0] weights_1_1_0_04_fu_126;
reg   [31:0] weights_1_1_1_05_fu_130;
reg   [31:0] weights_1_1_2_06_fu_134;
reg   [31:0] weights_1_2_0_07_fu_138;
reg   [31:0] weights_1_2_1_08_fu_142;
reg   [31:0] weights_1_2_2_09_fu_146;
reg   [31:0] weights_1_3_0_010_fu_150;
reg   [31:0] weights_1_3_1_011_fu_154;
reg   [31:0] weights_1_3_2_012_fu_158;
reg   [31:0] weights_1_4_0_013_fu_162;
reg   [31:0] weights_1_4_1_014_fu_166;
reg   [31:0] weights_1_4_2_015_fu_170;
reg   [31:0] weights_1_5_0_016_fu_174;
reg   [31:0] weights_1_5_1_017_fu_178;
reg   [31:0] weights_1_5_2_018_fu_182;
reg   [31:0] weights_1_6_0_019_fu_186;
reg   [31:0] weights_1_6_1_020_fu_190;
reg   [31:0] weights_1_6_2_021_fu_194;
reg   [31:0] weights_1_7_0_022_fu_198;
reg   [31:0] weights_1_7_1_023_fu_202;
reg   [31:0] weights_1_7_2_024_fu_206;
reg   [31:0] staged_fu_210;
wire    ap_CS_fsm_state1;
reg   [31:0] grp_fu_554_p0;
reg   [31:0] grp_fu_554_p1;
wire   [31:0] trunc_ln145_fu_974_p1;
wire   [7:0] tmp_fu_983_p4;
wire   [22:0] trunc_ln137_fu_993_p1;
wire   [0:0] or_ln137_fu_1009_p2;
wire   [0:0] grp_fu_554_p2;
wire   [0:0] and_ln137_fu_1013_p2;
reg    grp_fu_554_ce;
reg   [4:0] grp_fu_554_opcode;
wire   [31:0] grp_fu_1742_p2;
reg   [31:0] grp_fu_1742_p0;
reg   [31:0] grp_fu_1742_p1;
reg    grp_fu_1742_ce;
wire   [31:0] grp_fu_1746_p2;
reg    grp_fu_1746_ce;
wire   [31:0] grp_fu_1750_p2;
reg    grp_fu_1750_ce;
wire   [31:0] grp_fu_1754_p2;
reg    grp_fu_1754_ce;
wire   [31:0] grp_fu_1758_p2;
reg    grp_fu_1758_ce;
wire   [31:0] grp_fu_1762_p2;
reg    grp_fu_1762_ce;
wire   [31:0] grp_fu_1766_p2;
reg    grp_fu_1766_ce;
wire   [31:0] grp_fu_1770_p2;
reg    grp_fu_1770_ce;
wire   [31:0] grp_fu_1774_p2;
reg    grp_fu_1774_ce;
reg   [17:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
reg    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    regslice_both_S_AXIS_V_U_apdone_blk;
wire   [63:0] S_AXIS_V_TDATA_int_regslice;
wire    S_AXIS_V_TVALID_int_regslice;
reg    S_AXIS_V_TREADY_int_regslice;
wire    regslice_both_S_AXIS_V_U_ack_in;
wire    regslice_both_M_AXIS_V_U_apdone_blk;
wire    M_AXIS_V_TREADY_int_regslice;
wire    regslice_both_M_AXIS_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 18'd1;
#0 grp_mlp_dance3_Pipeline_layer0_fu_405_ap_start_reg = 1'b0;
#0 grp_mlp_dance3_Pipeline_retrieve_inputs_fu_428_ap_start_reg = 1'b0;
#0 grp_mlp_dance3_Pipeline_loadweights0_VITIS_LOOP_46_2_fu_435_ap_start_reg = 1'b0;
#0 grp_mlp_dance3_Pipeline_layer1_fu_442_ap_start_reg = 1'b0;
#0 grp_mlp_dance3_Pipeline_output_fu_484_ap_start_reg = 1'b0;
#0 grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_ap_start_reg = 1'b0;
#0 grp_mlp_dance3_Pipeline_loadbias0_fu_547_ap_start_reg = 1'b0;
end

mlp_dance3_input #(
    .DataWidth( 32 ),
    .AddressRange( 78 ),
    .AddressWidth( 7 ))
input_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(input_address0),
    .ce0(input_ce0),
    .we0(input_we0),
    .d0(grp_mlp_dance3_Pipeline_retrieve_inputs_fu_428_input_r_d0),
    .q0(input_q0),
    .address1(grp_mlp_dance3_Pipeline_layer0_fu_405_input_r_address1),
    .ce1(input_ce1),
    .q1(input_q1)
);

mlp_dance3_weights_0 #(
    .DataWidth( 32 ),
    .AddressRange( 624 ),
    .AddressWidth( 10 ))
weights_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(weights_0_address0),
    .ce0(weights_0_ce0),
    .we0(weights_0_we0),
    .d0(grp_mlp_dance3_Pipeline_loadweights0_VITIS_LOOP_46_2_fu_435_weights_0_d0),
    .q0(weights_0_q0),
    .address1(grp_mlp_dance3_Pipeline_layer0_fu_405_weights_0_address1),
    .ce1(weights_0_ce1),
    .q1(weights_0_q1)
);

mlp_dance3_bias_0 #(
    .DataWidth( 32 ),
    .AddressRange( 78 ),
    .AddressWidth( 7 ))
bias_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(bias_0_address0),
    .ce0(bias_0_ce0),
    .we0(bias_0_we0),
    .d0(grp_mlp_dance3_Pipeline_loadbias0_fu_547_bias_0_d0),
    .q0(bias_0_q0)
);

mlp_dance3_mlp_dance3_Pipeline_layer0 grp_mlp_dance3_Pipeline_layer0_fu_405(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_mlp_dance3_Pipeline_layer0_fu_405_ap_start),
    .ap_done(grp_mlp_dance3_Pipeline_layer0_fu_405_ap_done),
    .ap_idle(grp_mlp_dance3_Pipeline_layer0_fu_405_ap_idle),
    .ap_ready(grp_mlp_dance3_Pipeline_layer0_fu_405_ap_ready),
    .buffer_0_7_0553(buffer_0_7_0553_fu_98),
    .buffer_0_6_0552(buffer_0_6_0552_fu_94),
    .buffer_0_5_0551(buffer_0_5_0551_fu_90),
    .buffer_0_4_0550(buffer_0_4_0550_fu_86),
    .buffer_0_3_0549(buffer_0_3_0549_fu_82),
    .buffer_0_2_0548(buffer_0_2_0548_fu_78),
    .buffer_0_1_0547(buffer_0_1_0547_fu_74),
    .buffer_0_0_0546(buffer_0_0_0546_fu_70),
    .input_r_address0(grp_mlp_dance3_Pipeline_layer0_fu_405_input_r_address0),
    .input_r_ce0(grp_mlp_dance3_Pipeline_layer0_fu_405_input_r_ce0),
    .input_r_q0(input_q0),
    .input_r_address1(grp_mlp_dance3_Pipeline_layer0_fu_405_input_r_address1),
    .input_r_ce1(grp_mlp_dance3_Pipeline_layer0_fu_405_input_r_ce1),
    .input_r_q1(input_q1),
    .weights_0_address0(grp_mlp_dance3_Pipeline_layer0_fu_405_weights_0_address0),
    .weights_0_ce0(grp_mlp_dance3_Pipeline_layer0_fu_405_weights_0_ce0),
    .weights_0_q0(weights_0_q0),
    .weights_0_address1(grp_mlp_dance3_Pipeline_layer0_fu_405_weights_0_address1),
    .weights_0_ce1(grp_mlp_dance3_Pipeline_layer0_fu_405_weights_0_ce1),
    .weights_0_q1(weights_0_q1),
    .bias_0_address0(grp_mlp_dance3_Pipeline_layer0_fu_405_bias_0_address0),
    .bias_0_ce0(grp_mlp_dance3_Pipeline_layer0_fu_405_bias_0_ce0),
    .bias_0_q0(bias_0_q0),
    .buffer_0_7_1_out(grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_7_1_out),
    .buffer_0_7_1_out_ap_vld(grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_7_1_out_ap_vld),
    .buffer_0_6_1_out(grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_6_1_out),
    .buffer_0_6_1_out_ap_vld(grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_6_1_out_ap_vld),
    .buffer_0_5_1_out(grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_5_1_out),
    .buffer_0_5_1_out_ap_vld(grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_5_1_out_ap_vld),
    .buffer_0_4_1_out(grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_4_1_out),
    .buffer_0_4_1_out_ap_vld(grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_4_1_out_ap_vld),
    .buffer_0_3_1_out(grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_3_1_out),
    .buffer_0_3_1_out_ap_vld(grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_3_1_out_ap_vld),
    .buffer_0_2_1_out(grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_2_1_out),
    .buffer_0_2_1_out_ap_vld(grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_2_1_out_ap_vld),
    .buffer_0_1_1_out(grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_1_1_out),
    .buffer_0_1_1_out_ap_vld(grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_1_1_out_ap_vld),
    .buffer_0_0_1_out(grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_0_1_out),
    .buffer_0_0_1_out_ap_vld(grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_0_1_out_ap_vld),
    .grp_fu_1742_p_din0(grp_mlp_dance3_Pipeline_layer0_fu_405_grp_fu_1742_p_din0),
    .grp_fu_1742_p_din1(grp_mlp_dance3_Pipeline_layer0_fu_405_grp_fu_1742_p_din1),
    .grp_fu_1742_p_opcode(grp_mlp_dance3_Pipeline_layer0_fu_405_grp_fu_1742_p_opcode),
    .grp_fu_1742_p_dout0(grp_fu_1742_p2),
    .grp_fu_1742_p_ce(grp_mlp_dance3_Pipeline_layer0_fu_405_grp_fu_1742_p_ce),
    .grp_fu_554_p_din0(grp_mlp_dance3_Pipeline_layer0_fu_405_grp_fu_554_p_din0),
    .grp_fu_554_p_din1(grp_mlp_dance3_Pipeline_layer0_fu_405_grp_fu_554_p_din1),
    .grp_fu_554_p_opcode(grp_mlp_dance3_Pipeline_layer0_fu_405_grp_fu_554_p_opcode),
    .grp_fu_554_p_dout0(grp_fu_554_p2),
    .grp_fu_554_p_ce(grp_mlp_dance3_Pipeline_layer0_fu_405_grp_fu_554_p_ce)
);

mlp_dance3_mlp_dance3_Pipeline_retrieve_inputs grp_mlp_dance3_Pipeline_retrieve_inputs_fu_428(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_mlp_dance3_Pipeline_retrieve_inputs_fu_428_ap_start),
    .ap_done(grp_mlp_dance3_Pipeline_retrieve_inputs_fu_428_ap_done),
    .ap_idle(grp_mlp_dance3_Pipeline_retrieve_inputs_fu_428_ap_idle),
    .ap_ready(grp_mlp_dance3_Pipeline_retrieve_inputs_fu_428_ap_ready),
    .S_AXIS_V_TVALID(S_AXIS_V_TVALID_int_regslice),
    .S_AXIS_V_TDATA(S_AXIS_V_TDATA_int_regslice),
    .S_AXIS_V_TREADY(grp_mlp_dance3_Pipeline_retrieve_inputs_fu_428_S_AXIS_V_TREADY),
    .input_r_address0(grp_mlp_dance3_Pipeline_retrieve_inputs_fu_428_input_r_address0),
    .input_r_ce0(grp_mlp_dance3_Pipeline_retrieve_inputs_fu_428_input_r_ce0),
    .input_r_we0(grp_mlp_dance3_Pipeline_retrieve_inputs_fu_428_input_r_we0),
    .input_r_d0(grp_mlp_dance3_Pipeline_retrieve_inputs_fu_428_input_r_d0)
);

mlp_dance3_mlp_dance3_Pipeline_loadweights0_VITIS_LOOP_46_2 grp_mlp_dance3_Pipeline_loadweights0_VITIS_LOOP_46_2_fu_435(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_mlp_dance3_Pipeline_loadweights0_VITIS_LOOP_46_2_fu_435_ap_start),
    .ap_done(grp_mlp_dance3_Pipeline_loadweights0_VITIS_LOOP_46_2_fu_435_ap_done),
    .ap_idle(grp_mlp_dance3_Pipeline_loadweights0_VITIS_LOOP_46_2_fu_435_ap_idle),
    .ap_ready(grp_mlp_dance3_Pipeline_loadweights0_VITIS_LOOP_46_2_fu_435_ap_ready),
    .S_AXIS_V_TVALID(S_AXIS_V_TVALID_int_regslice),
    .weights_0_address0(grp_mlp_dance3_Pipeline_loadweights0_VITIS_LOOP_46_2_fu_435_weights_0_address0),
    .weights_0_ce0(grp_mlp_dance3_Pipeline_loadweights0_VITIS_LOOP_46_2_fu_435_weights_0_ce0),
    .weights_0_we0(grp_mlp_dance3_Pipeline_loadweights0_VITIS_LOOP_46_2_fu_435_weights_0_we0),
    .weights_0_d0(grp_mlp_dance3_Pipeline_loadweights0_VITIS_LOOP_46_2_fu_435_weights_0_d0),
    .S_AXIS_V_TDATA(S_AXIS_V_TDATA_int_regslice),
    .S_AXIS_V_TREADY(grp_mlp_dance3_Pipeline_loadweights0_VITIS_LOOP_46_2_fu_435_S_AXIS_V_TREADY)
);

mlp_dance3_mlp_dance3_Pipeline_layer1 grp_mlp_dance3_Pipeline_layer1_fu_442(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_mlp_dance3_Pipeline_layer1_fu_442_ap_start),
    .ap_done(grp_mlp_dance3_Pipeline_layer1_fu_442_ap_done),
    .ap_idle(grp_mlp_dance3_Pipeline_layer1_fu_442_ap_idle),
    .ap_ready(grp_mlp_dance3_Pipeline_layer1_fu_442_ap_ready),
    .buffer_1_2_027(buffer_1_2_027_fu_110),
    .buffer_1_1_026(buffer_1_1_026_fu_106),
    .buffer_1_0_025(buffer_1_0_025_fu_102),
    .weights_1_0_0_01(reg_679),
    .weights_1_0_1_02(reg_685),
    .weights_1_0_2_03(reg_691),
    .weights_1_1_0_04(reg_697),
    .weights_1_1_1_05(reg_703),
    .weights_1_1_2_06(reg_709),
    .weights_1_2_0_07(reg_715),
    .weights_1_2_1_08(reg_721),
    .weights_1_2_2_09(reg_727),
    .weights_1_3_0_010(reg_733),
    .weights_1_3_1_011(reg_739),
    .weights_1_3_2_012(reg_745),
    .weights_1_4_0_013(reg_751),
    .weights_1_4_1_014(reg_757),
    .weights_1_4_2_015(reg_763),
    .weights_1_5_0_016(reg_769),
    .weights_1_5_1_017(reg_775),
    .weights_1_5_2_018(reg_781),
    .weights_1_6_0_019(reg_787),
    .weights_1_6_1_020(reg_793),
    .weights_1_6_2_021(reg_799),
    .weights_1_7_0_022(reg_805),
    .weights_1_7_1_023(reg_811),
    .weights_1_7_2_024(reg_817),
    .buffer_0_0_1_reload(grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_0_1_out),
    .buffer_0_1_1_reload(grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_1_1_out),
    .buffer_0_2_1_reload(grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_2_1_out),
    .buffer_0_3_1_reload(grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_3_1_out),
    .buffer_0_4_1_reload(grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_4_1_out),
    .buffer_0_5_1_reload(grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_5_1_out),
    .buffer_0_6_1_reload(grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_6_1_out),
    .buffer_0_7_1_reload(grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_7_1_out),
    .buffer_1_2_1_out(grp_mlp_dance3_Pipeline_layer1_fu_442_buffer_1_2_1_out),
    .buffer_1_2_1_out_ap_vld(grp_mlp_dance3_Pipeline_layer1_fu_442_buffer_1_2_1_out_ap_vld),
    .buffer_1_1_1_out(grp_mlp_dance3_Pipeline_layer1_fu_442_buffer_1_1_1_out),
    .buffer_1_1_1_out_ap_vld(grp_mlp_dance3_Pipeline_layer1_fu_442_buffer_1_1_1_out_ap_vld),
    .buffer_1_0_1_out(grp_mlp_dance3_Pipeline_layer1_fu_442_buffer_1_0_1_out),
    .buffer_1_0_1_out_ap_vld(grp_mlp_dance3_Pipeline_layer1_fu_442_buffer_1_0_1_out_ap_vld),
    .grp_fu_1742_p_din0(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1742_p_din0),
    .grp_fu_1742_p_din1(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1742_p_din1),
    .grp_fu_1742_p_opcode(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1742_p_opcode),
    .grp_fu_1742_p_dout0(grp_fu_1742_p2),
    .grp_fu_1742_p_ce(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1742_p_ce),
    .grp_fu_1746_p_din0(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1746_p_din0),
    .grp_fu_1746_p_din1(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1746_p_din1),
    .grp_fu_1746_p_opcode(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1746_p_opcode),
    .grp_fu_1746_p_dout0(grp_fu_1746_p2),
    .grp_fu_1746_p_ce(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1746_p_ce),
    .grp_fu_1750_p_din0(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1750_p_din0),
    .grp_fu_1750_p_din1(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1750_p_din1),
    .grp_fu_1750_p_opcode(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1750_p_opcode),
    .grp_fu_1750_p_dout0(grp_fu_1750_p2),
    .grp_fu_1750_p_ce(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1750_p_ce),
    .grp_fu_1754_p_din0(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1754_p_din0),
    .grp_fu_1754_p_din1(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1754_p_din1),
    .grp_fu_1754_p_opcode(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1754_p_opcode),
    .grp_fu_1754_p_dout0(grp_fu_1754_p2),
    .grp_fu_1754_p_ce(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1754_p_ce),
    .grp_fu_1758_p_din0(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1758_p_din0),
    .grp_fu_1758_p_din1(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1758_p_din1),
    .grp_fu_1758_p_opcode(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1758_p_opcode),
    .grp_fu_1758_p_dout0(grp_fu_1758_p2),
    .grp_fu_1758_p_ce(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1758_p_ce),
    .grp_fu_1762_p_din0(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1762_p_din0),
    .grp_fu_1762_p_din1(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1762_p_din1),
    .grp_fu_1762_p_opcode(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1762_p_opcode),
    .grp_fu_1762_p_dout0(grp_fu_1762_p2),
    .grp_fu_1762_p_ce(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1762_p_ce),
    .grp_fu_1766_p_din0(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1766_p_din0),
    .grp_fu_1766_p_din1(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1766_p_din1),
    .grp_fu_1766_p_opcode(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1766_p_opcode),
    .grp_fu_1766_p_dout0(grp_fu_1766_p2),
    .grp_fu_1766_p_ce(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1766_p_ce),
    .grp_fu_1770_p_din0(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1770_p_din0),
    .grp_fu_1770_p_din1(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1770_p_din1),
    .grp_fu_1770_p_opcode(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1770_p_opcode),
    .grp_fu_1770_p_dout0(grp_fu_1770_p2),
    .grp_fu_1770_p_ce(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1770_p_ce),
    .grp_fu_1774_p_din0(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1774_p_din0),
    .grp_fu_1774_p_din1(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1774_p_din1),
    .grp_fu_1774_p_opcode(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1774_p_opcode),
    .grp_fu_1774_p_dout0(grp_fu_1774_p2),
    .grp_fu_1774_p_ce(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1774_p_ce),
    .grp_fu_554_p_din0(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_554_p_din0),
    .grp_fu_554_p_din1(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_554_p_din1),
    .grp_fu_554_p_opcode(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_554_p_opcode),
    .grp_fu_554_p_dout0(grp_fu_554_p2),
    .grp_fu_554_p_ce(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_554_p_ce)
);

mlp_dance3_mlp_dance3_Pipeline_output grp_mlp_dance3_Pipeline_output_fu_484(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_mlp_dance3_Pipeline_output_fu_484_ap_start),
    .ap_done(grp_mlp_dance3_Pipeline_output_fu_484_ap_done),
    .ap_idle(grp_mlp_dance3_Pipeline_output_fu_484_ap_idle),
    .ap_ready(grp_mlp_dance3_Pipeline_output_fu_484_ap_ready),
    .M_AXIS_V_TREADY(grp_mlp_dance3_Pipeline_output_fu_484_M_AXIS_V_TREADY),
    .buffer_1_0_1_reload(grp_mlp_dance3_Pipeline_layer1_fu_442_buffer_1_0_1_out),
    .buffer_1_1_1_reload(grp_mlp_dance3_Pipeline_layer1_fu_442_buffer_1_1_1_out),
    .buffer_1_2_1_reload(grp_mlp_dance3_Pipeline_layer1_fu_442_buffer_1_2_1_out),
    .M_AXIS_V_TDATA(grp_mlp_dance3_Pipeline_output_fu_484_M_AXIS_V_TDATA),
    .M_AXIS_V_TVALID(grp_mlp_dance3_Pipeline_output_fu_484_M_AXIS_V_TVALID)
);

mlp_dance3_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3 grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_ap_start),
    .ap_done(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_ap_done),
    .ap_idle(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_ap_idle),
    .ap_ready(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_ap_ready),
    .S_AXIS_V_TVALID(S_AXIS_V_TVALID_int_regslice),
    .weights_1_7_2_024(reg_817),
    .weights_1_7_1_023(reg_811),
    .weights_1_7_0_022(reg_805),
    .weights_1_6_2_021(reg_799),
    .weights_1_6_1_020(reg_793),
    .weights_1_6_0_019(reg_787),
    .weights_1_5_2_018(reg_781),
    .weights_1_5_1_017(reg_775),
    .weights_1_5_0_016(reg_769),
    .weights_1_4_2_015(reg_763),
    .weights_1_4_1_014(reg_757),
    .weights_1_4_0_013(reg_751),
    .weights_1_3_2_012(reg_745),
    .weights_1_3_1_011(reg_739),
    .weights_1_3_0_010(reg_733),
    .weights_1_2_2_09(reg_727),
    .weights_1_2_1_08(reg_721),
    .weights_1_2_0_07(reg_715),
    .weights_1_1_2_06(reg_709),
    .weights_1_1_1_05(reg_703),
    .weights_1_1_0_04(reg_697),
    .weights_1_0_2_03(reg_691),
    .weights_1_0_1_02(reg_685),
    .weights_1_0_0_01(reg_679),
    .S_AXIS_V_TDATA(S_AXIS_V_TDATA_int_regslice),
    .S_AXIS_V_TREADY(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_S_AXIS_V_TREADY),
    .weights_1_7_2_2_out(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_7_2_2_out),
    .weights_1_7_2_2_out_ap_vld(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_7_2_2_out_ap_vld),
    .weights_1_7_1_2_out(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_7_1_2_out),
    .weights_1_7_1_2_out_ap_vld(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_7_1_2_out_ap_vld),
    .weights_1_7_0_2_out(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_7_0_2_out),
    .weights_1_7_0_2_out_ap_vld(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_7_0_2_out_ap_vld),
    .weights_1_6_2_2_out(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_6_2_2_out),
    .weights_1_6_2_2_out_ap_vld(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_6_2_2_out_ap_vld),
    .weights_1_6_1_2_out(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_6_1_2_out),
    .weights_1_6_1_2_out_ap_vld(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_6_1_2_out_ap_vld),
    .weights_1_6_0_2_out(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_6_0_2_out),
    .weights_1_6_0_2_out_ap_vld(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_6_0_2_out_ap_vld),
    .weights_1_5_2_2_out(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_5_2_2_out),
    .weights_1_5_2_2_out_ap_vld(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_5_2_2_out_ap_vld),
    .weights_1_5_1_2_out(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_5_1_2_out),
    .weights_1_5_1_2_out_ap_vld(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_5_1_2_out_ap_vld),
    .weights_1_5_0_2_out(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_5_0_2_out),
    .weights_1_5_0_2_out_ap_vld(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_5_0_2_out_ap_vld),
    .weights_1_4_2_2_out(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_4_2_2_out),
    .weights_1_4_2_2_out_ap_vld(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_4_2_2_out_ap_vld),
    .weights_1_4_1_2_out(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_4_1_2_out),
    .weights_1_4_1_2_out_ap_vld(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_4_1_2_out_ap_vld),
    .weights_1_4_0_2_out(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_4_0_2_out),
    .weights_1_4_0_2_out_ap_vld(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_4_0_2_out_ap_vld),
    .weights_1_3_2_2_out(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_3_2_2_out),
    .weights_1_3_2_2_out_ap_vld(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_3_2_2_out_ap_vld),
    .weights_1_3_1_2_out(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_3_1_2_out),
    .weights_1_3_1_2_out_ap_vld(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_3_1_2_out_ap_vld),
    .weights_1_3_0_2_out(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_3_0_2_out),
    .weights_1_3_0_2_out_ap_vld(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_3_0_2_out_ap_vld),
    .weights_1_2_2_2_out(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_2_2_2_out),
    .weights_1_2_2_2_out_ap_vld(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_2_2_2_out_ap_vld),
    .weights_1_2_1_2_out(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_2_1_2_out),
    .weights_1_2_1_2_out_ap_vld(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_2_1_2_out_ap_vld),
    .weights_1_2_0_2_out(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_2_0_2_out),
    .weights_1_2_0_2_out_ap_vld(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_2_0_2_out_ap_vld),
    .weights_1_1_2_2_out(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_1_2_2_out),
    .weights_1_1_2_2_out_ap_vld(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_1_2_2_out_ap_vld),
    .weights_1_1_1_2_out(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_1_1_2_out),
    .weights_1_1_1_2_out_ap_vld(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_1_1_2_out_ap_vld),
    .weights_1_1_0_2_out(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_1_0_2_out),
    .weights_1_1_0_2_out_ap_vld(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_1_0_2_out_ap_vld),
    .weights_1_0_2_2_out(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_0_2_2_out),
    .weights_1_0_2_2_out_ap_vld(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_0_2_2_out_ap_vld),
    .weights_1_0_1_2_out(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_0_1_2_out),
    .weights_1_0_1_2_out_ap_vld(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_0_1_2_out_ap_vld),
    .weights_1_0_0_2_out(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_0_0_2_out),
    .weights_1_0_0_2_out_ap_vld(grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_0_0_2_out_ap_vld)
);

mlp_dance3_mlp_dance3_Pipeline_loadbias0 grp_mlp_dance3_Pipeline_loadbias0_fu_547(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_mlp_dance3_Pipeline_loadbias0_fu_547_ap_start),
    .ap_done(grp_mlp_dance3_Pipeline_loadbias0_fu_547_ap_done),
    .ap_idle(grp_mlp_dance3_Pipeline_loadbias0_fu_547_ap_idle),
    .ap_ready(grp_mlp_dance3_Pipeline_loadbias0_fu_547_ap_ready),
    .S_AXIS_V_TVALID(S_AXIS_V_TVALID_int_regslice),
    .S_AXIS_V_TDATA(S_AXIS_V_TDATA_int_regslice),
    .S_AXIS_V_TREADY(grp_mlp_dance3_Pipeline_loadbias0_fu_547_S_AXIS_V_TREADY),
    .bias_0_address0(grp_mlp_dance3_Pipeline_loadbias0_fu_547_bias_0_address0),
    .bias_0_ce0(grp_mlp_dance3_Pipeline_loadbias0_fu_547_bias_0_ce0),
    .bias_0_we0(grp_mlp_dance3_Pipeline_loadbias0_fu_547_bias_0_we0),
    .bias_0_d0(grp_mlp_dance3_Pipeline_loadbias0_fu_547_bias_0_d0)
);

mlp_dance3_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U162(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_554_p0),
    .din1(grp_fu_554_p1),
    .ce(grp_fu_554_ce),
    .opcode(grp_fu_554_opcode),
    .dout(grp_fu_554_p2)
);

mlp_dance3_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U163(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_1742_p0),
    .din1(grp_fu_1742_p1),
    .ce(grp_fu_1742_ce),
    .dout(grp_fu_1742_p2)
);

mlp_dance3_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U164(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1746_p_din0),
    .din1(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1746_p_din1),
    .ce(grp_fu_1746_ce),
    .dout(grp_fu_1746_p2)
);

mlp_dance3_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U165(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1750_p_din0),
    .din1(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1750_p_din1),
    .ce(grp_fu_1750_ce),
    .dout(grp_fu_1750_p2)
);

mlp_dance3_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U166(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1754_p_din0),
    .din1(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1754_p_din1),
    .ce(grp_fu_1754_ce),
    .dout(grp_fu_1754_p2)
);

mlp_dance3_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U167(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1758_p_din0),
    .din1(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1758_p_din1),
    .ce(grp_fu_1758_ce),
    .dout(grp_fu_1758_p2)
);

mlp_dance3_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U168(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1762_p_din0),
    .din1(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1762_p_din1),
    .ce(grp_fu_1762_ce),
    .dout(grp_fu_1762_p2)
);

mlp_dance3_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U169(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1766_p_din0),
    .din1(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1766_p_din1),
    .ce(grp_fu_1766_ce),
    .dout(grp_fu_1766_p2)
);

mlp_dance3_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U170(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1770_p_din0),
    .din1(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1770_p_din1),
    .ce(grp_fu_1770_ce),
    .dout(grp_fu_1770_p2)
);

mlp_dance3_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U171(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1774_p_din0),
    .din1(grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1774_p_din1),
    .ce(grp_fu_1774_ce),
    .dout(grp_fu_1774_p2)
);

mlp_dance3_regslice_both #(
    .DataWidth( 64 ))
regslice_both_S_AXIS_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(S_AXIS_V_TDATA),
    .vld_in(S_AXIS_V_TVALID),
    .ack_in(regslice_both_S_AXIS_V_U_ack_in),
    .data_out(S_AXIS_V_TDATA_int_regslice),
    .vld_out(S_AXIS_V_TVALID_int_regslice),
    .ack_out(S_AXIS_V_TREADY_int_regslice),
    .apdone_blk(regslice_both_S_AXIS_V_U_apdone_blk)
);

mlp_dance3_regslice_both #(
    .DataWidth( 64 ))
regslice_both_M_AXIS_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_mlp_dance3_Pipeline_output_fu_484_M_AXIS_V_TDATA),
    .vld_in(grp_mlp_dance3_Pipeline_output_fu_484_M_AXIS_V_TVALID),
    .ack_in(M_AXIS_V_TREADY_int_regslice),
    .data_out(M_AXIS_V_TDATA),
    .vld_out(regslice_both_M_AXIS_V_U_vld_out),
    .ack_out(M_AXIS_V_TREADY),
    .apdone_blk(regslice_both_M_AXIS_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_mlp_dance3_Pipeline_layer0_fu_405_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (staged_3_load_fu_828_p1 == 32'd4))) begin
            grp_mlp_dance3_Pipeline_layer0_fu_405_ap_start_reg <= 1'b1;
        end else if ((grp_mlp_dance3_Pipeline_layer0_fu_405_ap_ready == 1'b1)) begin
            grp_mlp_dance3_Pipeline_layer0_fu_405_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_mlp_dance3_Pipeline_layer1_fu_442_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_mlp_dance3_Pipeline_layer1_fu_442_ap_start_reg <= 1'b1;
        end else if ((grp_mlp_dance3_Pipeline_layer1_fu_442_ap_ready == 1'b1)) begin
            grp_mlp_dance3_Pipeline_layer1_fu_442_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_mlp_dance3_Pipeline_loadbias0_fu_547_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state16)) begin
            grp_mlp_dance3_Pipeline_loadbias0_fu_547_ap_start_reg <= 1'b1;
        end else if ((grp_mlp_dance3_Pipeline_loadbias0_fu_547_ap_ready == 1'b1)) begin
            grp_mlp_dance3_Pipeline_loadbias0_fu_547_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_mlp_dance3_Pipeline_loadweights0_VITIS_LOOP_46_2_fu_435_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (staged_3_load_fu_828_p1 == 32'd0))) begin
            grp_mlp_dance3_Pipeline_loadweights0_VITIS_LOOP_46_2_fu_435_ap_start_reg <= 1'b1;
        end else if ((grp_mlp_dance3_Pipeline_loadweights0_VITIS_LOOP_46_2_fu_435_ap_ready == 1'b1)) begin
            grp_mlp_dance3_Pipeline_loadweights0_VITIS_LOOP_46_2_fu_435_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_ap_start_reg <= 1'b1;
        end else if ((grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_ap_ready == 1'b1)) begin
            grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_mlp_dance3_Pipeline_output_fu_484_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_mlp_dance3_Pipeline_output_fu_484_ap_start_reg <= 1'b1;
        end else if ((grp_mlp_dance3_Pipeline_output_fu_484_ap_ready == 1'b1)) begin
            grp_mlp_dance3_Pipeline_output_fu_484_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_mlp_dance3_Pipeline_retrieve_inputs_fu_428_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (staged_3_load_fu_828_p1 == 32'd3))) begin
            grp_mlp_dance3_Pipeline_retrieve_inputs_fu_428_ap_start_reg <= 1'b1;
        end else if ((grp_mlp_dance3_Pipeline_retrieve_inputs_fu_428_ap_ready == 1'b1)) begin
            grp_mlp_dance3_Pipeline_retrieve_inputs_fu_428_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~(staged_3_load_fu_828_p1 == 32'd4) & ~(staged_3_load_fu_828_p1 == 32'd3) & ~(staged_3_load_fu_828_p1 == 32'd2) & ~(staged_3_load_fu_828_p1 == 32'd0) & ~(staged_3_load_fu_828_p1 == 32'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        staged_1_reg_386 <= staged_fu_210;
    end else if (((grp_mlp_dance3_Pipeline_retrieve_inputs_fu_428_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        staged_1_reg_386 <= 32'd4;
    end else if (((grp_mlp_dance3_Pipeline_output_fu_484_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        staged_1_reg_386 <= 32'd2;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        staged_1_reg_386 <= select_ln142_fu_1019_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        staged_2_reg_372 <= staged_1_reg_386;
    end else if (((1'b1 == ap_CS_fsm_state2) & (staged_3_load_fu_828_p1 == 32'd1))) begin
        staged_2_reg_372 <= 32'd1;
    end else if (((1'b0 == ap_block_state17_on_subcall_done) & (1'b1 == ap_CS_fsm_state17) & (staged_3_reg_1651 == 32'd0))) begin
        staged_2_reg_372 <= 32'd2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        staged_fu_210 <= 32'd0;
    end else if (((1'b0 == ap_block_state17_on_subcall_done) & (1'b1 == ap_CS_fsm_state17))) begin
        staged_fu_210 <= ap_phi_mux_staged_2_phi_fu_376_p6;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        buffer_0_0_0546_fu_70 <= grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_0_1_out;
        buffer_0_1_0547_fu_74 <= grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_1_1_out;
        buffer_0_2_0548_fu_78 <= grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_2_1_out;
        buffer_0_3_0549_fu_82 <= grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_3_1_out;
        buffer_0_4_0550_fu_86 <= grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_4_1_out;
        buffer_0_5_0551_fu_90 <= grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_5_1_out;
        buffer_0_6_0552_fu_94 <= grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_6_1_out;
        buffer_0_7_0553_fu_98 <= grp_mlp_dance3_Pipeline_layer0_fu_405_buffer_0_7_1_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        buffer_1_0_025_fu_102 <= grp_mlp_dance3_Pipeline_layer1_fu_442_buffer_1_0_1_out;
        buffer_1_1_026_fu_106 <= grp_mlp_dance3_Pipeline_layer1_fu_442_buffer_1_1_1_out;
        buffer_1_2_027_fu_110 <= grp_mlp_dance3_Pipeline_layer1_fu_442_buffer_1_2_1_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        icmp_ln137_1_reg_1732 <= icmp_ln137_1_fu_1003_p2;
        icmp_ln137_reg_1727 <= icmp_ln137_fu_997_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state4))) begin
        reg_679 <= weights_1_0_0_01_fu_114;
        reg_685 <= weights_1_0_1_02_fu_118;
        reg_691 <= weights_1_0_2_03_fu_122;
        reg_697 <= weights_1_1_0_04_fu_126;
        reg_703 <= weights_1_1_1_05_fu_130;
        reg_709 <= weights_1_1_2_06_fu_134;
        reg_715 <= weights_1_2_0_07_fu_138;
        reg_721 <= weights_1_2_1_08_fu_142;
        reg_727 <= weights_1_2_2_09_fu_146;
        reg_733 <= weights_1_3_0_010_fu_150;
        reg_739 <= weights_1_3_1_011_fu_154;
        reg_745 <= weights_1_3_2_012_fu_158;
        reg_751 <= weights_1_4_0_013_fu_162;
        reg_757 <= weights_1_4_1_014_fu_166;
        reg_763 <= weights_1_4_2_015_fu_170;
        reg_769 <= weights_1_5_0_016_fu_174;
        reg_775 <= weights_1_5_1_017_fu_178;
        reg_781 <= weights_1_5_2_018_fu_182;
        reg_787 <= weights_1_6_0_019_fu_186;
        reg_793 <= weights_1_6_1_020_fu_190;
        reg_799 <= weights_1_6_2_021_fu_194;
        reg_805 <= weights_1_7_0_022_fu_198;
        reg_811 <= weights_1_7_1_023_fu_202;
        reg_817 <= weights_1_7_2_024_fu_206;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        staged_3_reg_1651 <= staged_fu_210;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state17_on_subcall_done) & (1'b1 == ap_CS_fsm_state17) & (staged_3_reg_1651 == 32'd0))) begin
        weights_1_0_0_01_fu_114 <= grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_0_0_2_out;
        weights_1_0_1_02_fu_118 <= grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_0_1_2_out;
        weights_1_0_2_03_fu_122 <= grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_0_2_2_out;
        weights_1_1_0_04_fu_126 <= grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_1_0_2_out;
        weights_1_1_1_05_fu_130 <= grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_1_1_2_out;
        weights_1_1_2_06_fu_134 <= grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_1_2_2_out;
        weights_1_2_0_07_fu_138 <= grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_2_0_2_out;
        weights_1_2_1_08_fu_142 <= grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_2_1_2_out;
        weights_1_2_2_09_fu_146 <= grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_2_2_2_out;
        weights_1_3_0_010_fu_150 <= grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_3_0_2_out;
        weights_1_3_1_011_fu_154 <= grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_3_1_2_out;
        weights_1_3_2_012_fu_158 <= grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_3_2_2_out;
        weights_1_4_0_013_fu_162 <= grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_4_0_2_out;
        weights_1_4_1_014_fu_166 <= grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_4_1_2_out;
        weights_1_4_2_015_fu_170 <= grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_4_2_2_out;
        weights_1_5_0_016_fu_174 <= grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_5_0_2_out;
        weights_1_5_1_017_fu_178 <= grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_5_1_2_out;
        weights_1_5_2_018_fu_182 <= grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_5_2_2_out;
        weights_1_6_0_019_fu_186 <= grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_6_0_2_out;
        weights_1_6_1_020_fu_190 <= grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_6_1_2_out;
        weights_1_6_2_021_fu_194 <= grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_6_2_2_out;
        weights_1_7_0_022_fu_198 <= grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_7_0_2_out;
        weights_1_7_1_023_fu_202 <= grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_7_1_2_out;
        weights_1_7_2_024_fu_206 <= grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_weights_1_7_2_2_out;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        S_AXIS_V_TDATA_blk_n = S_AXIS_V_TVALID_int_regslice;
    end else begin
        S_AXIS_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) & (1'b1 == S_AXIS_V_TVALID_int_regslice))) begin
        S_AXIS_V_TREADY_int_regslice = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state17) & (staged_3_reg_1651 == 32'd0))) begin
        S_AXIS_V_TREADY_int_regslice = grp_mlp_dance3_Pipeline_loadbias0_fu_547_S_AXIS_V_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        S_AXIS_V_TREADY_int_regslice = grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_S_AXIS_V_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        S_AXIS_V_TREADY_int_regslice = grp_mlp_dance3_Pipeline_loadweights0_VITIS_LOOP_46_2_fu_435_S_AXIS_V_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        S_AXIS_V_TREADY_int_regslice = grp_mlp_dance3_Pipeline_retrieve_inputs_fu_428_S_AXIS_V_TREADY;
    end else begin
        S_AXIS_V_TREADY_int_regslice = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_mlp_dance3_Pipeline_loadweights0_VITIS_LOOP_46_2_fu_435_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

always @ (*) begin
    if ((grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_ap_done == 1'b0)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state17_on_subcall_done)) begin
        ap_ST_fsm_state17_blk = 1'b1;
    end else begin
        ap_ST_fsm_state17_blk = 1'b0;
    end
end

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state1_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_mlp_dance3_Pipeline_layer0_fu_405_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_mlp_dance3_Pipeline_layer1_fu_442_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_mlp_dance3_Pipeline_output_fu_484_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_mlp_dance3_Pipeline_retrieve_inputs_fu_428_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == S_AXIS_V_TVALID_int_regslice)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) & (staged_3_reg_1651 == 32'd0))) begin
        ap_phi_mux_staged_2_phi_fu_376_p6 = 32'd2;
    end else begin
        ap_phi_mux_staged_2_phi_fu_376_p6 = staged_2_reg_372;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) & (staged_3_reg_1651 == 32'd0))) begin
        bias_0_address0 = grp_mlp_dance3_Pipeline_loadbias0_fu_547_bias_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_0_address0 = grp_mlp_dance3_Pipeline_layer0_fu_405_bias_0_address0;
    end else begin
        bias_0_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) & (staged_3_reg_1651 == 32'd0))) begin
        bias_0_ce0 = grp_mlp_dance3_Pipeline_loadbias0_fu_547_bias_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_0_ce0 = grp_mlp_dance3_Pipeline_layer0_fu_405_bias_0_ce0;
    end else begin
        bias_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) & (staged_3_reg_1651 == 32'd0))) begin
        bias_0_we0 = grp_mlp_dance3_Pipeline_loadbias0_fu_547_bias_0_we0;
    end else begin
        bias_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        grp_fu_1742_ce = grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1742_p_ce;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        grp_fu_1742_ce = grp_mlp_dance3_Pipeline_layer0_fu_405_grp_fu_1742_p_ce;
    end else begin
        grp_fu_1742_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        grp_fu_1742_p0 = grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1742_p_din0;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        grp_fu_1742_p0 = grp_mlp_dance3_Pipeline_layer0_fu_405_grp_fu_1742_p_din0;
    end else begin
        grp_fu_1742_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        grp_fu_1742_p1 = grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1742_p_din1;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        grp_fu_1742_p1 = grp_mlp_dance3_Pipeline_layer0_fu_405_grp_fu_1742_p_din1;
    end else begin
        grp_fu_1742_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        grp_fu_1746_ce = grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1746_p_ce;
    end else begin
        grp_fu_1746_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        grp_fu_1750_ce = grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1750_p_ce;
    end else begin
        grp_fu_1750_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        grp_fu_1754_ce = grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1754_p_ce;
    end else begin
        grp_fu_1754_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        grp_fu_1758_ce = grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1758_p_ce;
    end else begin
        grp_fu_1758_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        grp_fu_1762_ce = grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1762_p_ce;
    end else begin
        grp_fu_1762_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        grp_fu_1766_ce = grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1766_p_ce;
    end else begin
        grp_fu_1766_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        grp_fu_1770_ce = grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1770_p_ce;
    end else begin
        grp_fu_1770_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        grp_fu_1774_ce = grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_1774_p_ce;
    end else begin
        grp_fu_1774_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        grp_fu_554_ce = grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_554_p_ce;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        grp_fu_554_ce = grp_mlp_dance3_Pipeline_layer0_fu_405_grp_fu_554_p_ce;
    end else if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state9) & (1'b1 == S_AXIS_V_TVALID_int_regslice)))) begin
        grp_fu_554_ce = 1'b1;
    end else begin
        grp_fu_554_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        grp_fu_554_opcode = grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_554_p_opcode;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        grp_fu_554_opcode = grp_mlp_dance3_Pipeline_layer0_fu_405_grp_fu_554_p_opcode;
    end else if (((1'b1 == ap_CS_fsm_state9) & (1'b1 == S_AXIS_V_TVALID_int_regslice))) begin
        grp_fu_554_opcode = 5'd1;
    end else begin
        grp_fu_554_opcode = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        grp_fu_554_p0 = grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_554_p_din0;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        grp_fu_554_p0 = grp_mlp_dance3_Pipeline_layer0_fu_405_grp_fu_554_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_554_p0 = in_data_fu_978_p1;
    end else begin
        grp_fu_554_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        grp_fu_554_p1 = grp_mlp_dance3_Pipeline_layer1_fu_442_grp_fu_554_p_din1;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        grp_fu_554_p1 = grp_mlp_dance3_Pipeline_layer0_fu_405_grp_fu_554_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_554_p1 = 32'd0;
    end else begin
        grp_fu_554_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        input_address0 = grp_mlp_dance3_Pipeline_retrieve_inputs_fu_428_input_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_address0 = grp_mlp_dance3_Pipeline_layer0_fu_405_input_r_address0;
    end else begin
        input_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        input_ce0 = grp_mlp_dance3_Pipeline_retrieve_inputs_fu_428_input_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_ce0 = grp_mlp_dance3_Pipeline_layer0_fu_405_input_r_ce0;
    end else begin
        input_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_ce1 = grp_mlp_dance3_Pipeline_layer0_fu_405_input_r_ce1;
    end else begin
        input_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        input_we0 = grp_mlp_dance3_Pipeline_retrieve_inputs_fu_428_input_r_we0;
    end else begin
        input_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        weights_0_address0 = grp_mlp_dance3_Pipeline_loadweights0_VITIS_LOOP_46_2_fu_435_weights_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        weights_0_address0 = grp_mlp_dance3_Pipeline_layer0_fu_405_weights_0_address0;
    end else begin
        weights_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        weights_0_ce0 = grp_mlp_dance3_Pipeline_loadweights0_VITIS_LOOP_46_2_fu_435_weights_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        weights_0_ce0 = grp_mlp_dance3_Pipeline_layer0_fu_405_weights_0_ce0;
    end else begin
        weights_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        weights_0_ce1 = grp_mlp_dance3_Pipeline_layer0_fu_405_weights_0_ce1;
    end else begin
        weights_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        weights_0_we0 = grp_mlp_dance3_Pipeline_loadweights0_VITIS_LOOP_46_2_fu_435_weights_0_we0;
    end else begin
        weights_0_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            if ((~(staged_3_load_fu_828_p1 == 32'd4) & ~(staged_3_load_fu_828_p1 == 32'd3) & ~(staged_3_load_fu_828_p1 == 32'd2) & ~(staged_3_load_fu_828_p1 == 32'd0) & ~(staged_3_load_fu_828_p1 == 32'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else if (((1'b1 == ap_CS_fsm_state2) & (staged_3_load_fu_828_p1 == 32'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else if (((1'b1 == ap_CS_fsm_state2) & (staged_3_load_fu_828_p1 == 32'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else if (((1'b1 == ap_CS_fsm_state2) & (staged_3_load_fu_828_p1 == 32'd2))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else if (((1'b1 == ap_CS_fsm_state2) & (staged_3_load_fu_828_p1 == 32'd3))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_mlp_dance3_Pipeline_layer0_fu_405_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_mlp_dance3_Pipeline_layer1_fu_442_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((grp_mlp_dance3_Pipeline_output_fu_484_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((grp_mlp_dance3_Pipeline_retrieve_inputs_fu_428_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (1'b1 == S_AXIS_V_TVALID_int_regslice))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state11 : begin
            if (((grp_mlp_dance3_Pipeline_loadweights0_VITIS_LOOP_46_2_fu_435_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if (((grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            if (((1'b0 == ap_block_state17_on_subcall_done) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign M_AXIS_V_TVALID = regslice_both_M_AXIS_V_U_vld_out;

assign S_AXIS_V_TREADY = regslice_both_S_AXIS_V_U_ack_in;

assign and_ln137_fu_1013_p2 = (or_ln137_fu_1009_p2 & grp_fu_554_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state17_on_subcall_done = ((grp_mlp_dance3_Pipeline_loadbias0_fu_547_ap_done == 1'b0) & (staged_3_reg_1651 == 32'd0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_mlp_dance3_Pipeline_layer0_fu_405_ap_start = grp_mlp_dance3_Pipeline_layer0_fu_405_ap_start_reg;

assign grp_mlp_dance3_Pipeline_layer1_fu_442_ap_start = grp_mlp_dance3_Pipeline_layer1_fu_442_ap_start_reg;

assign grp_mlp_dance3_Pipeline_loadbias0_fu_547_ap_start = grp_mlp_dance3_Pipeline_loadbias0_fu_547_ap_start_reg;

assign grp_mlp_dance3_Pipeline_loadweights0_VITIS_LOOP_46_2_fu_435_ap_start = grp_mlp_dance3_Pipeline_loadweights0_VITIS_LOOP_46_2_fu_435_ap_start_reg;

assign grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_ap_start = grp_mlp_dance3_Pipeline_loadweights1_VITIS_LOOP_52_3_fu_493_ap_start_reg;

assign grp_mlp_dance3_Pipeline_output_fu_484_M_AXIS_V_TREADY = (ap_CS_fsm_state7 & M_AXIS_V_TREADY_int_regslice);

assign grp_mlp_dance3_Pipeline_output_fu_484_ap_start = grp_mlp_dance3_Pipeline_output_fu_484_ap_start_reg;

assign grp_mlp_dance3_Pipeline_retrieve_inputs_fu_428_ap_start = grp_mlp_dance3_Pipeline_retrieve_inputs_fu_428_ap_start_reg;

assign icmp_ln137_1_fu_1003_p2 = ((trunc_ln137_fu_993_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln137_fu_997_p2 = ((tmp_fu_983_p4 != 8'd255) ? 1'b1 : 1'b0);

assign in_data_fu_978_p1 = trunc_ln145_fu_974_p1;

assign or_ln137_fu_1009_p2 = (icmp_ln137_reg_1727 | icmp_ln137_1_reg_1732);

assign select_ln142_fu_1019_p3 = ((and_ln137_fu_1013_p2[0:0] == 1'b1) ? 32'd3 : 32'd5);

assign staged_3_load_fu_828_p1 = staged_fu_210;

assign tmp_fu_983_p4 = {{S_AXIS_V_TDATA_int_regslice[30:23]}};

assign trunc_ln137_fu_993_p1 = S_AXIS_V_TDATA_int_regslice[22:0];

assign trunc_ln145_fu_974_p1 = S_AXIS_V_TDATA_int_regslice[31:0];

endmodule //mlp_dance3
